### ISSUE TITLE
question regarding minimize all on Mac OS Sonoma

### ISSUE THREAD

**Issue by JosefGvirt** [wellCh4n/Minimize-All-Windows#1]
Kind regards, a cool workflow! I noticed when I tried it on Mac OS Sonoma, it only minimized the forefront window and closed the windows of all other apps. Do you know if this is the intended result? thanks.

**Comment by wellCh4n** [comment]
> Kind regards, a cool workflow! I noticed when I tried it on Mac OS Sonoma, it only minimized the forefront window and closed the windows of all other apps. Do you know if this is the intended result? thanks.

Hi, this is a workflow I did a long time ago, but I am trying to reproduce this environment to give you an answer. Keep focus on this issue plz!

**Comment by wellCh4n** [comment]
Hi, @JosefGvirt 
First of all, I'm very sorry that I don't have a Mac OS Sonoma device. But, I took a look at the source code and this workflow is helping us to trigger two hot-keys:
* **Option + Command + H**: To view the front app but hide all other apps
* **Command + M**: Minimize the front window to the Dock

So when this command is triggered, you'll see the other apps hide and see the minimize animation of the front app at the same time.
Is this the same as what you observed? Looking forward to your reply.

Reference: https://support.apple.com/en-hk/HT201236

**Comment by JosefGvirt** [comment]
Hey @wellCh4n , thank you very much for taking your time and 

> Hi, @JosefGvirt First of all, I'm very sorry that I don't have a Mac OS Sonoma device. But, I took a look at the source code and this workflow is helping us to trigger two hot-keys:
> 
> * **Option + Command + H**: To view the front app but hide all other apps
> * **Command + M**: Minimize the front window to the Dock
> 
> So when this command is triggered, you'll see the other apps hide and see the minimize animation of the front app at the same time. Is this the same as what you observed? Looking forward to your reply.
> 
> Reference: https://support.apple.com/en-hk/HT201236

**Comment by JosefGvirt** [comment]
@wellCh4n thank you so much for replying and your time, so exactly, it does what you wrote.
